# Generated by Django 4.2.1 on 2023-05-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_category_remove_product_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
